export const getNumberOfImg = state => state.numberOfImg
export const getTimePassedAfterStart = state => state.timePassedAfterStart
export const getTimePassedAfterFlip = state => state.timePassedAfterFlip
export const getTimerInterval = state => state.timerInterval
export const getSizeOfImg = state => state.sizeOfImg
export const getGameMode = state => state.gameMode
export const getSearchValue = state => state.searchValue
export const getToRememberImgArray = state => state.toRememberImgArray
export const getToGuessImgArray = state => state.toGuessImgArray
export const getDataFetched = state => state.dataFetched
export const getSecondsToRemember = state => state.secondsToRemember
export const getTimerEnd = state => state.timerEnd
